### ISSUE TITLE
Support for ecto 3.0

### ISSUE THREAD

**Issue by vraravam** [zven21/turbo_ecto#22]
I am trying out a `phoenix 1.4` codebase, and for that, the `ecto` is `3.0`. Due to the constaints on this package, I'm unable to use it. Could you please upgrade and release a new version?

**Comment by vraravam** [comment]
@zven21 - I have progressed a little bit towards this - but not enough yet for a PR. My forked code is [here](https://github.com/vraravam/turbo_ecto/tree/ecto3), could you please review and tell me how I can proceed?

**Comment by zven21** [comment]
@vraravam I have fixed it, but I am still refactoring. If you need it, you can use

```elixir
{:turbo_ecto, github: "zven21/turbo_ecto"},
{:turbo_html, github: "zven21/turbo_html"}
```

**Comment by vraravam** [comment]
thanks - I will give it a try over the weekend when I have a little bit of time.
