### ISSUE TITLE
Support for Ecto 3.

### ISSUE THREAD

**Issue by Preen** [zven21/turbo_ecto#26]
Hi!
Wonder if there's any plans to create a public release for supporting Ecto 3. As our library is dependent on your library and we want to upgrade to Ecto 3 (hex wont allow for any non released packages afaik) it would be awesome if it can happen :)

https://github.com/FLEWID-AB/alkemist/pull/24

**Comment by zven21** [comment]
@Preen okay, I updated `turbo_ecto` to version `0.2.1`,  it's support ecto 3, because ecto 3  search API has changed, so only ecto 3 + is supported.

**Comment by zven21** [comment]
At the same time, I added an [example](https://github.com/zven21/turbo_ecto#demo) and updated the view [turbo_html](https://github.com/zven21/turbo_html)

**Comment by Preen** [comment]
Thank you very much!
