### ISSUE TITLE
Raise actual error reason during search

### ISSUE THREAD

**Issue by segaz2002** [zven21/turbo_ecto#58]
In the scenario where a search field is not part for the schema(queryable) supplied to turboq/2, here is the current result in the case of an error `(RuntimeError) Expected `params`, got %{"q" => %{"name_like" => "son"}, "s" => "inserted_at+asc"}` raised from https://github.com/zven21/turbo_ecto/blob/ff3566e97d42cbb5d49634ec78acdd4a9fbefc39/lib/turbo_ecto/builder.ex#L99

Current error is generic and does not help in terms of debugging issues.

I will suggest returning the exact error reason from the tuple (:error, reason) returned from the with clause execution e.g https://github.com/zven21/turbo_ecto/blob/ff3566e97d42cbb5d49634ec78acdd4a9fbefc39/lib/turbo_ecto/hooks/search/attribute.ex#L23 currently this is being silenced and a generic error message is returned.

A solution can be to match against the returned error reason atom and provide human readable error messages. Something like;

```elixir
def run(queryable, params) do
    schema = extract_schema(queryable)
    params = Utils.stringify_keys(params)

    with {:ok, %Search{} = searches} <- Search.run(schema, params),
         {:ok, sorts} <- Sort.run(schema, params),
         {:ok, %Paginate{} = %{limit: limit, offset: offset}} <- Paginate.run(params) do
      relations = build_relations(searches, sorts)
      binding = relations |> build_binding()

      queryable
      |> join(relations)
      |> where(searches, binding)
      |> order_by(sorts, binding)
      |> limit(limit, binding)
      |> offset(offset, binding)
    else
      {:error, :attribute_not_found} -> raise "One or more keys in your search are not contained or can't be linked to the specified schema"
      {:error, _} -> raise "Expected `params`, got #{inspect(params)}"
    end
  end
```

**Comment by zven21** [comment]
Sorry to reply to you only now, `{:turbo_ecto, "~> 0.6.2"}` supports this feature.
